"""Minimal local Host: contracts, Conductor delegation, gate and presentation."""
import getpass
import hmac
import json
import os
import secrets
import subprocess
import sys
import threading
import time
import uuid
from pathlib import Path

from nexus.contracts import ROOT, Blocked, strict_json, validate
from nexus.store import Store, HumanDecision, atomic, digest


def verify_integrity():
    manifest = strict_json((ROOT / "integrity.json").read_bytes())
    required = {
        "__init__.py", "app.py", "host.py", "store.py", "contracts.py", "approval_binding.py", "instance.py",
        "adapters/conductor_runner.py", "adapters/tools.py", "adapters/notebook.py",
        "adapters/languagetool.py", "adapters/office.py",
        "laws/CONSTITUTION.md", "laws/policy.json",
        "processes/check.yaml", "processes/verify.yaml", "processes/interpret.yaml",
        "processes/proofread.yaml", "processes/convert_pdf.yaml",
        "schemas/request.json", "schemas/result.json", "schemas/cognitive.json", "schemas/languagetool.json",
        "ui/index.html", "ui/app.js", "ui/style.css",
        "adapters/constitutional.py", "processes/register_object.yaml", "schemas/multimedia.json",
        "families/multimedia/som.md", "families/multimedia/imagem.md",
    }
    if not isinstance(manifest, dict) or set(manifest) != required:
        raise Blocked("Manifesto de integridade ausente ou incompleto.")
    for relative, expected in manifest.items():
        target = ROOT / relative
        if target.is_symlink() or digest(target.read_bytes()) != expected:
            raise Blocked("Um contrato ou processo mudou. É necessária revisão antes de executar.")
    return manifest


def process_environment(run_directory):
    # No inherited credentials, provider settings, user prompts or host session.
    keep = ("SystemRoot", "WINDIR", "COMSPEC", "SYSTEMDRIVE")
    environment = {key: os.environ[key] for key in keep if key in os.environ}
    environment.update(
        PATH=str(Path(sys.executable).parent) + os.pathsep + str(Path(os.environ["SystemRoot"]) / "System32"),
        TEMP=str(run_directory), TMP=str(run_directory), PYTHONUTF8="1", PYTHONIOENCODING="utf-8",
        PSModuleAnalysisCachePath=str((Path(run_directory) / "powershell-module-analysis-cache").resolve()),
    )
    return environment


class Host:
    def __init__(self, data_root):
        verify_integrity()
        self.store = Store(data_root)
        self.session = secrets.token_urlsafe(32)
        self.tickets = {}
        self.busy = threading.Lock()
        self.actor = getpass.getuser()

    def authorize(self, session):
        if not isinstance(session, str) or not hmac.compare_digest(session, self.session):
            raise Blocked("Abre a Folha através do lançador local.")

    def start(self, request, session):
        self.authorize(session)
        verify_integrity()
        if not self.busy.acquire(blocking=False):
            raise Blocked("Já há um pedido a executar. Aguarda o resultado.")
        try:
            run_id = self.store.create(request)
        except Exception:
            self.busy.release()
            raise
        threading.Thread(target=self._run, args=(run_id,), daemon=True).start()
        return {"run_id": run_id}

    def _run(self, run_id):
        directory = self.store.path("runs", run_id)
        state = self.store.state(run_id)
        try:
            process = state["process_id"]
            if process == "interpret":
                # Configuration is local and administrative, never generated by IA.
                config = self.store.root / "open-notebook.json"
                if not config.exists():
                    raise Blocked("A interpretação ainda precisa de Open Notebook e de um modelo local configurados.")
                atomic(directory / "open-notebook.json", config.read_bytes())
            if process == "proofread":
                config = self.store.root / "languagetool.json"
                if not config.is_file():
                    raise Blocked("A revisão precisa de Java e LanguageTool configurados localmente.")
                atomic(directory / "languagetool.json", config.read_bytes())
            if process == "convert_pdf":
                config = self.store.root / "libreoffice.json"
                if not config.is_file():
                    raise Blocked("LibreOffice precisa de configuração local.")
                atomic(directory / "libreoffice.json", config.read_bytes())
            command = [sys.executable, "-I", str(ROOT / "adapters/conductor_runner.py"), process, str(directory / "input.bin")]
            env = process_environment(directory)
            proc = subprocess.Popen(command, cwd=directory, env=env, stdin=subprocess.DEVNULL,
                                    stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                    creationflags=subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0)
            try:
                stdout, stderr = proc.communicate(timeout=150 if process == "interpret" else 75)
            except subprocess.TimeoutExpired:
                if os.name == "nt":
                    subprocess.run([str(Path(os.environ["SystemRoot"]) / "System32/taskkill.exe"),
                                    "/PID", str(proc.pid), "/T", "/F"], capture_output=True, timeout=10)
                proc.kill()
                proc.communicate()
                raise Blocked("A ferramenta excedeu o tempo permitido.")
            atomic(directory / "execution.stderr.txt", stderr)
            atomic(directory / "execution.stdout.json", stdout)
            if proc.returncode:
                raise Blocked("A execução da ferramenta falhou. O diagnóstico foi guardado.")
            if not stdout.strip():
                raise Blocked("A ferramenta não devolveu um resultado.")
            envelope = strict_json(stdout)
            if not isinstance(envelope, dict) or set(envelope) != {"result", "trace"}:
                raise Blocked("Resposta de execução inválida.")
            envelope["trace"]["workflow_sha256"] = digest((ROOT / "processes" / (process + ".yaml")).read_bytes())
            self.store.accept(run_id, envelope["result"], envelope["trace"])
        except Exception as error:
            self.store.update(run_id, status="BLOCKED" if isinstance(error, Blocked) else "FAIL",
                              message=str(error) if isinstance(error, Blocked) else "Não foi possível concluir. O pedido foi conservado.")
            atomic(directory / "failure.json", {"type": type(error).__name__, "message": str(error)})
        finally:
            try:
                (directory / "open-notebook.json").unlink(missing_ok=True)
            except OSError:
                self.store.update(run_id, status="BLOCKED", message="Não foi possível remover a credencial temporária. Requer intervenção local.")
            finally:
                self.busy.release()

    def list_runs(self, session):
        self.authorize(session)
        values = [strict_json(p.read_bytes()) for p in (self.store.root / "runs").glob("*/state.json")]
        return sorted(values, key=lambda item: item["created_at"], reverse=True)

    def detail(self, run_id, session):
        self.authorize(session)
        state = self.store.state(run_id)
        candidate = self.store.path("creative", run_id)
        if (candidate / "result.json").exists():
            result = strict_json((candidate / "result.json").read_bytes())
            state["result"] = result
            state["content"] = (candidate / "content.md").read_text("utf-8")
        return state

    def artifact(self, run_id, session):
        self.authorize(session)
        state = self.store.state(run_id)
        data = self.store.verify_artifact(state, self.store.path("creative", run_id))
        if data is None:
            raise Blocked("Este resultado não tem PDF.")
        return data

    def prepare_approval(self, run_id, session):
        self.authorize(session)
        with self.store.lock:
            state = self.store.state(run_id)
            if state["status"] != "HUMAN_REQUIRED":
                raise Blocked("Não há candidato pendente de decisão.")
            self.store.verify_artifact(state, self.store.path("creative", run_id))
            content = (self.store.path("creative", run_id) / "content.md").read_bytes()
            if digest(content) != state["candidate_sha256"]:
                raise Blocked("O conteúdo mudou. A aprovação foi bloqueada.")
            # Keep only live tickets for other candidates; refreshing revokes the old review.
            current_time = time.monotonic()
            self.tickets = {key: value for key, value in self.tickets.items()
                            if value[2] > current_time and value[0] != run_id}
            ticket = secrets.token_urlsafe(32)
            self.tickets[ticket] = (run_id, digest(content), time.monotonic() + 300)
            return {"ticket": ticket, "content": content.decode("utf-8")}

    def approve(self, run_id, ticket, confirmed, session):
        self.authorize(session)
        with self.store.lock:
            binding = self.tickets.pop(ticket, None) if isinstance(ticket, str) else None
            if confirmed is not True or not binding or binding[0] != run_id or binding[2] < time.monotonic():
                raise Blocked("BLOCK: é necessária confirmação humana explícita.")
            decision = HumanDecision(uuid.uuid4().hex, self.actor, run_id, binding[1], "APPROVE")
            return self.store.promote(run_id, decision)
